linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
  disable:
    - deadcode # временно отключаем более строгие проверки
    - unused
    - structcheck

run:
  deadline: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck