name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install dependencies
      run: go mod download
        
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --disable=staticcheck,deadcode,unused,structcheck --timeout=5m
        skip-pkg-cache: true
        skip-build-cache: true
        skip-cache: true
        only-new-issues: false
        
    - name: Build
      run: go build -v ./...
      
    - name: Test
      run: go test -v ./...
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: websocket-dump:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max